apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo-app-with-springboot-on-k8s
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: todo-app-with-springboot-on-k8s
      labels:
        app: todo-app-with-springboot-on-k8s
    spec:
      containers:
      - name: todo-app-with-springboot-on-k8s
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: masterslave/todo-app-with-springboot-on-k8s:v1
